### ISSUE TITLE
Configurable USB Joystick interface - v2.7

### ISSUE THREAD

**Issue by banyaszg** [banyaszg/edgetx#1]
**This is version 2.7.1**
**Current version:** https://github.com/banyaszg/edgetx/issues/2

### Overview

The existing USB HID Joystick interface is a static one. The device acts as a GamePad. The first 8 channels are handled as axes (X, Y, Z, rotX, rotY, rotZ, slider, slider), and the remaining 24 channels reported as push buttons.
Usually this way is ok, but there could be issues.
- Some operating systems and softwares handle axes differently loosing some of them. So it would be fine if we could relabel the axes and use as many as we would like.
- The handling of the 3 state switches is problematic. Reporting as an axis doesn't fit into existing softwares. Reporting as a push button we lose a state. However we can create logical switches for each state, but it is complicated to configure.

### The solution I'd like

- I would like a configurable USB Joystick interface where I can specify the type of the interface, and the reporting mode of each channel.
- It would nice if I could have different settings for each models. This way we can make specific model setting for a PC software.
- This is only a secondary function, so the user interface should be discrete and minimalist. (One more setting in the model settings page, and one in the channel mixer.)

### Tasks

- [x] Storing the interface type and the channel modes in the model settings.
- [x] Generating YAML storage codes.
- [x] Settings initialization for new models.
- [ ] ~~Settings conversion for old model settings.~~
- [x] GUI 128x64 implementation of settings.
- [x] GUI 212x64 implementation of settings.
- [x] GUI color implementation of settings.
  - [ ] Disabling settings during the USB communication, and position settings if not switch mode is selected.
- [x] Disabling editing during the USB connection.
- [x] English string constants.
- [x] Copy string constants to other translations.
- [x] Creating HID report description from the model settings.
  - [x] Some axes should be unique, because the PC OS driver can not handle more than one. (OSs are different in this.) The user can define multiple ones, but they will overwrite each other.  
  - [x] Some axes are part of the Generic Desktop page, some of them are Simulation Controls.
- [x] Creating HID report.
- [x] Hook the HID report description and HID report into the existing USB Joystick driver.
- [x] Changing model can change the USB Joystick interface settings.
  - [x] Checking whether the new HID report description / report is the same as the old one.
  - [x] When the new interface is different, then the software should disconnect and reconnect as USB Joystick. Stability tests are needed.
- [x] ~~6P~~ Multiposition switch support.
  - [x] Redesign the button/switch type. There would be one type with a position number parameter.
  - [x] Storage modification
  - [x] GUI modifications
  - [x] Translation modifications
  - [x] USB Report Description modifications
  - [x] USB Report modification
- [ ] Companion support for settings.
- [x] Clean up commented code.
- [x] Updating the code to fit into the main branch.
  - [ ] Rewriting of the color GUI.
